# Generated by Django 5.1.6 on 2025-02-25 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('O', 'Orgânico'), ('R', 'Reciclável'), ('N', 'Não Reciclável')], max_length=1)),
                ('quantidade', models.FloatField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coleta', models.DateTimeField()),
                ('localizacao', models.CharField(max_length=255)),
                ('residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residuos.residuo')),
            ],
        ),
    ]
