# Generated by Django 5.1.6 on 2025-03-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0002_recompensa_residuo_pontos_residuo_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleta',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
    ]
