# Generated by Django 5.1.6 on 2025-03-01 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0003_coleta_pontos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coleta',
            name='pontos',
        ),
        migrations.RemoveField(
            model_name='residuo',
            name='pontos',
        ),
        migrations.AlterField(
            model_name='residuo',
            name='tipo',
            field=models.CharField(choices=[('O', 'Orgânico'), ('R', 'Reciclável'), ('N', 'Não Reciclável'), ('L', 'Latinha'), ('F', 'Ferro'), ('P', 'Papelão')], max_length=1),
        ),
        migrations.AlterField(
            model_name='residuo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
