# Generated by Django 5.1.6 on 2025-03-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0004_remove_coleta_pontos_remove_residuo_pontos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recompensa',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
